CREATE TABLE IF NOT EXISTS pppoe_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    package_id INT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    status ENUM('active','disabled') DEFAULT 'active',
    comment VARCHAR(100) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
