<?php
require_once 'config.php';
$conn = db();

function generateClientsConf($conn) {
    $result = $conn->query("SELECT * FROM nas ORDER BY id");
    $clients = $result->fetch_all(MYSQLI_ASSOC);

    $conf = "# Auto-generated by Hotspot Billing - Do not edit manually\n\n";
    $conf .= "client localhost {\n";
    $conf .= "\tipaddr = 127.0.0.1\n";
    $conf .= "\tsecret = testing123\n";
    $conf .= "\tshortname = localhost\n";
    $conf .= "\tnas_type = other\n";
    $conf .= "}\n\n";
    $conf .= "client localhost_ipv6 {\n";
    $conf .= "\tipv6addr = ::1\n";
    $conf .= "\tsecret = testing123\n";
    $conf .= "}\n\n";

    foreach ($clients as $c) {
        $name = preg_replace('/[^a-zA-Z0-9_-]/', '_', $c['shortname'] ?: $c['nasname']);
        $conf .= "client $name {\n";
        $conf .= "\tipaddr = " . $c['nasname'] . "\n";
        $conf .= "\tsecret = \"" . $c['secret'] . "\"\n";
        $conf .= "\tshortname = " . ($c['shortname'] ?: $name) . "\n";
        $conf .= "\tnas_type = " . ($c['type'] ?: 'other') . "\n";
        $conf .= "\trequire_message_authenticator = true\n";
        $conf .= "}\n\n";
    }

    file_put_contents('/etc/freeradius/3.0/clients.conf', $conf);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    if ($action === 'save_whatsapp') {
        $api_url = trim($_POST['api_url'] ?? '');
        $api_key = trim($_POST['api_key'] ?? '');
        $sender_phone = trim($_POST['sender_phone'] ?? '');
        $provider = $_POST['provider'] ?? 'fonnte';
        $is_active = isset($_POST['is_active']) ? 1 : 0;

        $escUrl = $conn->real_escape_string($api_url);
        $escKey = $conn->real_escape_string($api_key);
        $escPhone = $conn->real_escape_string($sender_phone);
        $escProv = $conn->real_escape_string($provider);

        $exists = $conn->query("SELECT id FROM whatsapp_settings LIMIT 1");
        if ($exists->num_rows > 0) {
            $conn->query("UPDATE whatsapp_settings SET api_url='$escUrl', api_key='$escKey', sender_phone='$escPhone', provider='$escProv', is_active=$is_active WHERE id=1");
        } else {
            $conn->query("INSERT INTO whatsapp_settings (api_url, api_key, sender_phone, provider, is_active) VALUES ('$escUrl', '$escKey', '$escPhone', '$escProv', $is_active)");
        }

        setFlash('WhatsApp settings berhasil disimpan.', 'success');
        header('Location: settings.php#whatsapp');
        exit;
    }

    if ($action === 'save_template') {
        $tpl_id = intval($_POST['template_id'] ?? 0);
        $message = trim($_POST['message'] ?? '');

        $escMsg = $conn->real_escape_string($message);
        $conn->query("UPDATE wa_templates SET message='$escMsg', updated_at=NOW() WHERE id=$tpl_id");

        setFlash('Template berhasil disimpan.', 'success');
        header('Location: settings.php#whatsapp');
        exit;
    }

    if ($action === 'test_wa') {
        $test_phone = trim($_POST['test_phone'] ?? '');
        if (empty($test_phone)) {
            setFlash('Nomor HP wajib diisi untuk test.', 'danger');
            header('Location: settings.php#whatsapp');
            exit;
        }
        require_once 'includes/wa_helper.php';
        $result = waSend($test_phone, 'Test notifikasi dari Hotspot Billing. Jika Anda menerima pesan ini, WhatsApp API sudah berfungsi.');
        if ($result['ok']) {
            setFlash('Test WhatsApp berhasil terkirim ke ' . $test_phone, 'success');
        } else {
            setFlash('Test WhatsApp gagal: ' . ($result['msg'] ?? 'Unknown error'), 'danger');
        }
        header('Location: settings.php#whatsapp');
        exit;
    }

    if ($action === 'add') {
        $nasname = trim($_POST['nasname'] ?? '');
        $shortname = trim($_POST['shortname'] ?? '');
        $secret = trim($_POST['secret'] ?? '');
        $type = trim($_POST['type'] ?? 'other');

        if (empty($nasname) || empty($secret)) {
            setFlash('IP/Range dan Secret wajib diisi.', 'danger');
            header('Location: settings.php');
            exit;
        }

        $escNas = $conn->real_escape_string($nasname);
        $escShort = $conn->real_escape_string($shortname);
        $escSecret = $conn->real_escape_string($secret);
        $escType = $conn->real_escape_string($type);

        $conn->query("INSERT INTO nas (nasname, shortname, type, secret) VALUES ('$escNas', '$escShort', '$escType', '$escSecret')");

        generateClientsConf($conn);
        exec('sudo /usr/bin/systemctl restart freeradius 2>&1', $output, $ret);

        setFlash("NAS '$nasname' berhasil ditambahkan." . ($ret === 0 ? '' : ' (restart gagal)'), 'success');
        header('Location: settings.php');
        exit;
    }

    if ($action === 'edit') {
        $id = intval($_POST['id'] ?? 0);
        $nasname = trim($_POST['nasname'] ?? '');
        $shortname = trim($_POST['shortname'] ?? '');
        $secret = trim($_POST['secret'] ?? '');
        $type = trim($_POST['type'] ?? 'other');

        if (empty($nasname) || empty($secret)) {
            setFlash('IP/Range dan Secret wajib diisi.', 'danger');
            header('Location: settings.php');
            exit;
        }

        $escNas = $conn->real_escape_string($nasname);
        $escShort = $conn->real_escape_string($shortname);
        $escSecret = $conn->real_escape_string($secret);
        $escType = $conn->real_escape_string($type);

        $conn->query("UPDATE nas SET nasname='$escNas', shortname='$escShort', secret='$escSecret', type='$escType' WHERE id=$id");

        generateClientsConf($conn);
        exec('sudo /usr/bin/systemctl restart freeradius 2>&1', $output, $ret);

        setFlash("NAS ID $id berhasil diupdate." . ($ret === 0 ? '' : ' (restart gagal)'), 'success');
        header('Location: settings.php');
        exit;
    }

    if ($action === 'delete') {
        $id = intval($_POST['id'] ?? 0);
        $conn->query("DELETE FROM nas WHERE id = $id");

        generateClientsConf($conn);
        exec('sudo /usr/bin/systemctl restart freeradius 2>&1', $output, $ret);

        setFlash("NAS berhasil dihapus." . ($ret === 0 ? '' : ' (restart gagal)'), 'success');
        header('Location: settings.php');
        exit;
    }
}

$nasList = $conn->query("SELECT * FROM nas ORDER BY id")->fetch_all(MYSQLI_ASSOC);
$waSettings = $conn->query("SELECT * FROM whatsapp_settings LIMIT 1")->fetch_assoc();
$waTemplates = $conn->query("SELECT * FROM wa_templates ORDER BY id")->fetch_all(MYSQLI_ASSOC);

require_once 'includes/header.php';
?>

<h4 class="mb-4"><i class="fas fa-cog"></i> Settings</h4>

<ul class="nav nav-tabs mb-3" id="settingsTab">
    <li class="nav-item"><a class="nav-link active" data-bs-toggle="tab" href="#nas">NAS Clients</a></li>
    <li class="nav-item"><a class="nav-link" data-bs-toggle="tab" href="#whatsapp">WhatsApp</a></li>
</ul>

<div class="tab-content">
<div class="tab-pane fade show active" id="nas">
<div class="card shadow-sm mb-4">
    <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
        <span><i class="fas fa-server"></i> NAS Clients (RADIUS)</span>
        <button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#nasModal" onclick="resetNasForm()">
            <i class="fas fa-plus"></i> Tambah NAS
        </button>
    </div>
    <div class="card-body p-0">
        <table class="table table-hover mb-0 align-middle">
            <thead class="table-light">
                <tr>
                    <th width="50">ID</th>
                    <th>IP / Range</th>
                    <th>Short Name</th>
                    <th>Type</th>
                    <th>Secret</th>
                    <th width="120">Aksi</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($nasList)): ?>
                <tr><td colspan="6" class="text-center text-muted py-4">Belum ada NAS client</td></tr>
                <?php else: ?>
                <?php foreach ($nasList as $nas): ?>
                <tr>
                    <td><?= $nas['id'] ?></td>
                    <td><code><?= htmlspecialchars($nas['nasname']) ?></code></td>
                    <td><?= htmlspecialchars($nas['shortname']) ?></td>
                    <td><span class="badge bg-secondary"><?= htmlspecialchars($nas['type'] ?: 'other') ?></span></td>
                    <td><code><?= htmlspecialchars($nas['secret']) ?></code></td>
                    <td>
                        <button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#nasModal"
                            onclick="editNas(<?= $nas['id'] ?>, '<?= htmlspecialchars(addslashes($nas['nasname'])) ?>', '<?= htmlspecialchars(addslashes($nas['shortname'])) ?>', '<?= htmlspecialchars(addslashes($nas['secret'])) ?>', '<?= htmlspecialchars(addslashes($nas['type'] ?: 'other')) ?>')">
                            <i class="fas fa-edit"></i>
                        </button>
                        <form method="POST" class="d-inline" onsubmit="return confirm('Hapus NAS ini?')">
                            <input type="hidden" name="action" value="delete">
                            <input type="hidden" name="id" value="<?= $nas['id'] ?>">
                            <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
</div>

<div class="tab-pane fade" id="whatsapp">
<div class="card shadow-sm mb-4">
    <div class="card-header bg-success text-white"><i class="fab fa-whatsapp"></i> WhatsApp API Settings</div>
    <div class="card-body">
        <form method="POST">
            <input type="hidden" name="action" value="save_whatsapp">
            <div class="row">
                <div class="col-md-4 mb-3">
                    <label class="form-label">Provider</label>
                    <select name="provider" class="form-select">
                        <option value="fonnte" <?= ($waSettings['provider'] ?? '') === 'fonnte' ? 'selected' : '' ?>>Fonnte.com</option>
                        <option value="wablas" <?= ($waSettings['provider'] ?? '') === 'wablas' ? 'selected' : '' ?>>Wablas.com</option>
                        <option value="manual" <?= ($waSettings['provider'] ?? '') === 'manual' ? 'selected' : '' ?>>Manual (Custom API)</option>
                    </select>
                </div>
                <div class="col-md-4 mb-3">
                    <label class="form-label">Status</label>
                    <div class="form-check form-switch mt-2">
                        <input class="form-check-input" type="checkbox" name="is_active" value="1" <?= ($waSettings['is_active'] ?? 0) ? 'checked' : '' ?>>
                        <label class="form-check-label">Aktifkan Notifikasi WhatsApp</label>
                    </div>
                </div>
                <div class="col-md-4 mb-3">
                    <label class="form-label">Sender Phone</label>
                    <input type="text" name="sender_phone" class="form-control" value="<?= htmlspecialchars($waSettings['sender_phone'] ?? '') ?>" placeholder="628xxxxxxxxxx">
                    <small class="text-muted">Format: 628xxx tanpa +</small>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 mb-3">
                    <label class="form-label">API URL</label>
                    <input type="url" name="api_url" class="form-control" value="<?= htmlspecialchars($waSettings['api_url'] ?? '') ?>" placeholder="https://api.fonnte.com/send">
                </div>
                <div class="col-md-4 mb-3">
                    <label class="form-label">API Key</label>
                    <input type="text" name="api_key" class="form-control" value="<?= htmlspecialchars($waSettings['api_key'] ?? '') ?>" placeholder="API Key / Token">
                </div>
            </div>
            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i> Simpan Settings</button>
        </form>
    </div>
</div>

<div class="card shadow-sm mb-4">
    <div class="card-header"><i class="fas fa-vial"></i> Test WhatsApp</div>
    <div class="card-body">
        <form method="POST" class="row g-2 align-items-end">
            <input type="hidden" name="action" value="test_wa">
            <div class="col-md-6">
                <label class="form-label">Nomor HP Tujuan</label>
                <input type="text" name="test_phone" class="form-control" placeholder="08xxxxxxxxxx">
            </div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-success"><i class="fab fa-whatsapp"></i> Kirim Test</button>
            </div>
        </form>
    </div>
</div>

<div class="card shadow-sm mb-4">
    <div class="card-header bg-dark text-white"><i class="fas fa-file-alt"></i> Template Message</div>
    <div class="card-body">
        <div class="alert alert-info mb-3">
            <i class="fas fa-info-circle"></i> <strong>Variable yang tersedia:</strong><br>
            <code>{nama}</code> Nama pelanggan &nbsp;|&nbsp; <code>{username}</code> Username &nbsp;|&nbsp; <code>{password}</code> Password<br>
            <code>{periode}</code> Bulan/Tahun &nbsp;|&nbsp; <code>{amount}</code> Jumlah bayar &nbsp;|&nbsp; <code>{due_date}</code> Tgl jatuh tempo &nbsp;|&nbsp; <code>{package}</code> Nama paket
        </div>

        <?php foreach ($waTemplates as $tpl): ?>
        <form method="POST" class="mb-3">
            <input type="hidden" name="action" value="save_template">
            <input type="hidden" name="template_id" value="<?= $tpl['id'] ?>">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <strong><i class="fas fa-tag"></i> <?= htmlspecialchars($tpl['template_name']) ?></strong>
                    <small class="text-muted">Vars: <?= htmlspecialchars($tpl['variables']) ?></small>
                </div>
                <div class="card-body">
                    <textarea name="message" class="form-control" rows="4"><?= htmlspecialchars($tpl['message']) ?></textarea>
                </div>
                <div class="card-footer text-end">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fas fa-save"></i> Simpan</button>
                </div>
            </div>
        </form>
        <?php endforeach; ?>
    </div>
</div>

<div class="alert alert-success">
    <i class="fas fa-info-circle"></i>
    <strong>Cara Setup:</strong>
    <ol class="mb-0 mt-1">
        <li><strong>Fonnte:</strong> Daftar di <a href="https://fonnte.com" target="_blank">fonnte.com</a> → Dashboard → API Token → Copy</li>
        <li><strong>Wablas:</strong> Daftar di <a href="https://wablas.com" target="_blank">wablas.com</a> → API Token → Copy</li>
        <li>Paste API Key, isi Sender Phone (628xxx)</li>
        <li>Edit template, aktifkan toggle, klik <strong>Kirim Test</strong></li>
    </ol>
</div>
</div>
</div>

<div class="modal fade" id="nasModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" id="nasForm">
                <input type="hidden" name="action" id="nasAction" value="add">
                <input type="hidden" name="id" id="nasId" value="">
                <div class="modal-header">
                    <h5 class="modal-title" id="nasModalTitle"><i class="fas fa-server"></i> Tambah NAS</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">IP / Range <span class="text-danger">*</span></label>
                        <input type="text" name="nasname" id="nasIp" class="form-control" required placeholder="172.16.2.1">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Short Name</label>
                        <input type="text" name="shortname" id="nasShortname" class="form-control" placeholder="mikrotik">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Secret <span class="text-danger">*</span></label>
                        <input type="text" name="secret" id="nasSecret" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Type</label>
                        <select name="type" id="nasType" class="form-select">
                            <option value="other">other</option>
                            <option value="mikrotik">mikrotik</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
function resetNasForm() {
    document.getElementById('nasForm').reset();
    document.getElementById('nasAction').value = 'add';
    document.getElementById('nasId').value = '';
    document.getElementById('nasModalTitle').innerHTML = '<i class="fas fa-server"></i> Tambah NAS';
}
function editNas(id, ip, shortname, secret, type) {
    document.getElementById('nasAction').value = 'edit';
    document.getElementById('nasId').value = id;
    document.getElementById('nasIp').value = ip;
    document.getElementById('nasShortname').value = shortname;
    document.getElementById('nasSecret').value = secret;
    document.getElementById('nasType').value = type;
    document.getElementById('nasModalTitle').innerHTML = '<i class="fas fa-server"></i> Edit NAS #' + id;
}
</script>

<?php require_once 'includes/footer.php'; ?>
